### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by Irtiza90**
sorted imports to be first stdlib modules, then other
added main function

### CODE REVIEW

**Review by was07 — APPROVED** [review]
looking good

**Comment by was07** [comment]
Hey a thing, I know you through discord right, i forgot your discord profile?

**Comment by Irtiza90** [comment]
> Hey a thing, I know you through discord right, i forgot your discord profile?

It's DarkRex4

**Comment by was07** [comment]
oh OK

**Comment by Irtiza90** [comment]
> oh OK

In the Python Discord

**Pull request merged**
