### PR TITLE
refactor code and re-structure imports

### PR DESCRIPTION
**Pull request by Irtiza90**
Refactored the Code with `black`
and some small refactor changes:
  - made subclasses of `ast_parser.Node` to directly inherit and set position of the token(*start, and end[Optional]*)
  - also fixed issue in which(in shell mode) pressing `Enter`(with no characters typed) would raise an exception

### CODE REVIEW

**Review by was07 — APPROVED** [review]
Nice Work! Will get approved after some quick tests.

**Comment by Irtiza90** [comment]
previously `Cyan` looked like a python package, but it was actually not(except the *\_\_init__ and \_\_main__* modules)
everything was imported like a normal python **module**, instead of using `package.module`.

**Comment by was07** [comment]
But seems like the `from Cyan import something` isn't working if I try to run Cyan as I normally would:
```
Traceback (most recent call last):
  File "C:\Users\MN\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MN\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Cyan\Cyan\__main__.py", line 4, in <module>
    from Cyan import __version__
ModuleNotFoundError: No module named 'Cyan
```

**Comment by Irtiza90** [comment]
> 

try `python -m Cyan`

**Pull request merged**
